modLoader="javafml"
loaderVersion="[36.2,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/kmfisk/HotChicks/issues"

[[mods]]
    modId="hotchicks"
    version="${file.jarVersion}"
    displayName="Click for Hot Chicks"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://github.com/kmfisk/HotChicks/wiki"
    logoFile="icon.png"
    credits="SnazzyGator, barca, TheMapleMoose, Coda, P-plum, RyanHCode"
    authors="kmfisk, Mnesikos"
    description='''Find ancestor livestock animals to care for and selectively breed into domestic variants, new crops to help feed you and your animals, and craft fun new blocks and items including barn blocks and an assortment of foods!'''

[[dependencies.hotchicks]]
    modId="forge"
    mandatory=true
    versionRange="[36.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hotchicks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
