# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="hotchicks" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Click for Hot Chicks" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="Huge thank you to the following people for their contributions!! RyanHCode, moose/elan, and barca." #optional
# A text field displayed in the mod UI
authors="kmfisk, Mnesikos" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
click for hot chicks is a really nice mod with a really awful name.

release 1 is going to be focused on breeding and raising healthy, happy chickens. there are 8 domestic chicken breeds that you can breed from the wild ancestor, the red junglefowl.

to get chickens, find a pair of junglefowl (they spawn in dark forests, jungles, and other lush forest biomes) and breed them. check their tameness stat with a stud book, and breed birds with higher and higher tameness till you get to 85%: once you do, you'll get a domestic chicken! junglefowl can drop meat and lay eggs, but don't drop much and don't lay fun, valuable colors.

you'll need a nest or nest box for your chickens to lay eggs in. breed the two you'd like to have a chick, and leave the egg in the nest for a full minecraft day - removing it makes it unviable, so be careful! if you do remove an egg, you can always use it for cooking and crafting.

what chicken breed you get depends on the biome you're in: different biomes make for differently adapted breeds with different base stats. chickens have stats that decide how much meat, how many eggs, and what color eggs they make, so keep that in mind when you decide what you want to breed. leghorns lay lots of eggs, but rhode islands reds have better meat. stats generally average between the parents, with a chance for random "mutation."

you can also find crops to feed yourself and your birds. wild versions of crops spawn uncommonly: just break one, and plant the food you get on farmland or on a crafted trellis block.

there's more to come from hot chicks, so keep your eyes open!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.hotchicks]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.hotchicks]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
